### PR TITLE
Update 01_Known_Issues_and_Limitations_2015_Volume_2.md

### PR DESCRIPTION
**Pull request by hanastasov**

### CODE REVIEW

**Comment by damyanpetev** [comment]
@hanastasov If that's an 15.2 limitation applied to the 15.2 file.. should it not be merged in 15.2 branch instead? Just checking, because PR-s automatically go for the default branch which might not be the intent.. happened to me too recently :)

**Comment by hanastasov** [comment]
Yup, thats valid for 15.2 as well,I guess the title which says 2015_Volume_2 confused me.

**Comment by kdinev** [comment]
Should this one still be merged, or is it the same as #77 ?

**Comment by hanastasov** [comment]
It's the same

**Comment by hanastasov** [comment]
Same as  [#77](https://github.com/IgniteUI/help-topics/pull/77) , closing

**Pull request closed without merging**
